version: '3'
services:
  postgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=url_shortening
      - POSTGRES_USER=docker
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/bitnami/postgresql'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=docker
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'

volumes:
  postgres_data:
  redis_data: